### ISSUE TITLE
Тикет для художников - рисовать гробы

### ISSUE THREAD

**Issue by yule44ka** [Hardes1/nup24#1]
Нарисовать призрака
Нарисовать гробы, в которые поместится призрак
Анимация прохождения через объекты
Все в 3Д

**Comment by dimaStepul** [comment]
authors:
- foxkids33
- dimaStepul

**Comment by InnocentusLime** [comment]
Добрый дкнь

**Comment by alpdk** [comment]
![20240320_203837](https://github.com/zulman/nup24/assets/61936617/e8cde174-5090-4d3b-a14a-7d9244ea891a)

Гроб готов!!!

**Comment by dimaStepul** [comment]
https://drive.google.com/file/d/17SnGHVH8HNNRexKdtTy5KRCs_h5PRbxt/view?usp=sharing
Unity supports importing Meshes and animation from two different types of files: Exported 3D file formats, such as . fbx or . obj.

**Comment by alpdk** [comment]
What do you wnat from me?

**Comment by yule44ka** [comment]
https://free3d.com/ru/3d-models/blender

**Comment by yule44ka** [comment]
https://free3d.com/ru/3d-models/unity

**Comment by yule44ka** [comment]
@alpdk Добавь 3д модельку, как это сделал Кеша. Она должна быть более прямоугольной. Не забудь отправить ее разработчикам :)

**Comment by polimer-consumer** [comment]
Гробы залиты

**Comment by InnocentusLime** [comment]
Призрак
https://drive.google.com/drive/folders/1RUGyB-oOY3vo90ibOIR9wVZ46qTlt6hK?usp=sharing

**Comment by yule44ka** [comment]
Призрак с головой, вытянутый и белый и чуть-чуть прозрачный (старую модельку оставить на будущее)
