### ISSUE TITLE
3д монетка

### ISSUE THREAD

**Issue by yule44ka** [Hardes1/nup24#5]
Нарисовать 3D монтеки
https://free3d.com/ru/3d-models/unity 3D!!!!!!!

**Comment by yule44ka** [comment]
https://free3d.com/ru/3d-models/unity

**Comment by dimaStepul** [comment]
тикет назначен foxkids33

**Comment by 92pIus2** [comment]
Монета не может выглядеть как блин, на монете всегда есть бортик, либо ребристые края!
